name: workflow-ci-cd
on:
  push:
    branches:
     - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install package.json
        run: |
          yarn install

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Restart application
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{secrets.PRIVATE_SSH_KEY}}
          script: |
            cd ci-cd-aula
            git pull
            pm2 restart ci-cd-aula
